import type { Config } from 'tailwindcss'

export default {
  // Nuxt 4 : le contenu est dans app/
  content: [
    './app/**/*.{vue,ts,js,tsx}',
    './app/components/**/*.{vue,ts}',
    './app/pages/**/*.vue',
    './app/layouts/**/*.vue',
  ],
  theme: {
    extend: {
      colors: {
        'primary':                   '#003e7e',
        'primary-container':         '#1a56a0',
        'primary-dark':              '#0d3a6e',
        'primary-light':             '#ebf4fb',
        'primary-medium':            '#2e75b6',
        'on-primary':                '#ffffff',
        'on-primary-container':      '#b3cdff',
        'primary-fixed':             '#d6e3ff',
        'primary-fixed-dim':         '#a9c7ff',
        'on-primary-fixed':          '#001b3d',
        'on-primary-fixed-variant':  '#00468c',
        'secondary':                 '#576065',
        'secondary-container':       '#dbe4eb',
        'on-secondary':              '#ffffff',
        'on-secondary-container':    '#5d666c',
        'secondary-fixed':           '#dbe4eb',
        'secondary-fixed-dim':       '#bfc8ce',
        'tertiary':                  '#153f74',
        'tertiary-container':        '#32578d',
        'on-tertiary':               '#ffffff',
        'on-tertiary-container':     '#b2ceff',
        'tertiary-fixed':            '#d5e3ff',
        'tertiary-fixed-dim':        '#a8c8ff',
        'on-tertiary-fixed':         '#001b3c',
        'on-tertiary-fixed-variant': '#1f477c',
        'background':                '#f8f9ff',
        'on-background':             '#0b1c30',
        'surface':                   '#f8f9ff',
        'on-surface':                '#0b1c30',
        'surface-variant':           '#d3e4fe',
        'on-surface-variant':        '#424751',
        'surface-container-low':     '#eff4ff',
        'surface-container':         '#e5eeff',
        'surface-container-high':    '#dce9ff',
        'surface-container-lowest':  '#ffffff',
        'surface-bright':            '#f8f9ff',
        'surface-dim':               '#cbdbf5',
        'outline':                   '#737782',
        'outline-variant':           '#c2c6d3',
        'error':                     '#ba1a1a',
        'error-container':           '#ffdad6',
        'on-error':                  '#ffffff',
        'on-error-container':        '#93000a',
        'inverse-surface':           '#213145',
        'inverse-on-surface':        '#eaf1ff',
        'inverse-primary':           '#a9c7ff',
        'surface-tint':              '#265ea8',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
      },
      spacing: {
        'margin-mobile':  '20px',
        'margin-desktop': '64px',
        'stack-sm':       '8px',
        'stack-md':       '16px',
        'stack-lg':       '24px',
        'stack-xl':       '40px',
        'section-gap':    '80px',
        'gutter':         '24px',
      },
      fontSize: {
        'display-lg':         ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg':        ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-md':        ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg':            ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':            ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md':           ['14px', { lineHeight: '1',   letterSpacing: '0.05em', fontWeight: '600' }],
        'caption':            ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
} satisfies Config
